nginx:
  image: nginx:latest
  ports:
    - 80:80
  links:
    - php
  volumes:
    - ./www/html:/var/www/html

php:
  image: php:7.0-fpm
  expose:
    - 9000
  volumes:
    - ./www/html:/var/www/html
